### PR TITLE
Added messed up mobs

### PR DESCRIPTION
**Pull request by NathanSalapat**
Some of the animals are upside down, other backwards, and other are both upside down and backwards. I also changed around some of the drops, expect to get cobble and saplings, glass bottles, other weird stuff.

### CODE REVIEW

**Comment by Cat5TV** [comment]
Hahaha Sounds amazing @NathanSalapat - thanks!

**Comment by Cat5TV** [comment]
The mobs_redo submodule isn't working (the link doesn't seem to be active) so I disabled that version on my local copy and activated our server-wide mobs_redo and all is well, but not seeing any mobs. Any insight into either issue? I'm new to submodules, but the one I did for Don's cutepie mod worked.

**Comment by Cat5TV** [comment]
I fixed the submodule (was missing the destination path from the command line syntax... git submodule add https://github.com/tenplus1/mobs_redo **mods/mobs_redo**)
Working on getting the mobs_crappy working, which was conflicting with 'mobs' and mobs_animals.

**Comment by Cat5TV** [comment]
This is truly awesome @NathanSalapat  -- thanks again!! Working great now.

**Comment by NathanSalapat** [comment]
I've never used submodules, so I probable messed up royally on that. I thought it would be as easy as just putting an exact copy of that mod in the folder, I guess not. Glad you got it working.

**Comment by Cat5TV** [comment]
No worries @NathanSalapat -- it's all new to me too, and I did the same mistake, so that's how I knew how to fix it  :) 

The correct command is: git submodule add https://github.com/tenplus1/mobs_redo mods/mobs_redo

Key thing to remember is to also specify the output folder. Otherwise, it'll clone normally on your local copy, but the submodule won't work on a recursive pull.

Great work with this mod! Only issue we've spotted is that the cow needs to be raised one node (he's hidden in the ground).

**Comment by NathanSalapat** [comment]
I'll have to brush up on my git, so I can fast forward my fork to be even with the master, and then change the collision box on the cow so it's above ground. I didn't test any of the code before pushing the changes.

**Comment by Cat5TV** [comment]
You're a madman!  ;)

I'm _happy of myself_ that I'm at least at the point with Lua that when something's broke, I can fix it. So the mod in its current form in the master branch works great. You'll need to do a new pull. And the only issue I know of is the cow being 1 node into the ground. :)

**Pull request merged**
