### PR TITLE
uploaded skins

### PR DESCRIPTION
**Pull request by dkelley810**
uploaded more skins

### CODE REVIEW

**Comment by dkelley810** [comment]
not sure if i did this right

**Comment by Cat5TV** [comment]
Hey dkelley810, Github says "This branch has conflicts that must be resolved
 Use the command line" - have you had a chance to fix that and re-pull? Would love to get the additional skins. Feel free to email me a zip file if it's easier.
Thanks!!
Robbie

**Comment by dkelley810** [comment]
Robbie,

I zipped them up.

I have a sleep study appointment tonight. So I am getting ready for that.

Please let me know if there is anything else you need from me!

Thanks
Dennis

**Comment by Cat5TV** [comment]
Thanks Dennis. I did not receive the zip yet.

**Comment by dkelley810** [comment]
Its on its way

**Comment by Cat5TV** [comment]
Thanks man. Great job!

**Pull request closed without merging**
